local CONSTANTS = {}

CONSTANTS.TYPE_GEM_BLUE = 1
CONSTANTS.TYPE_GEM_YELLOW = 2
CONSTANTS.TYPE_GEM_RED = 3
CONSTANTS.TYPE_GEM_GREEN = 4
CONSTANTS.TYPE_GEM_PINK = 5
CONSTANTS.TYPE_GEM_WHITE = 6

CONSTANTS.SCREEN_WIDTH = 640
CONSTANTS.SCREEN_HEIGHT = 960

CONSTANTS.TILE_SIZE = 60
CONSTANTS.GRID_SIZE_X = 8
CONSTANTS.GRID_SIZE_Y = 11
CONSTANTS.GRID_SPACE = 6

CONSTANTS.Z_GRID = 1
CONSTANTS.Z_SWAP_1 = 2
CONSTANTS.Z_SWAP_2 = 3
CONSTANTS.Z_DIAMOND = 4



CONSTANTS.TYPES = { CONSTANTS.TYPE_GEM_BLUE, CONSTANTS.TYPE_GEM_YELLOW, CONSTANTS.TYPE_GEM_RED, CONSTANTS.TYPE_GEM_GREEN, CONSTANTS.TYPE_GEM_PINK }


CONSTANTS.POINTS = 10;
CONSTANTS.COMBO_POINTS = 50;
CONSTANTS.DIAMOND_POINTS = 100;

return CONSTANTS



